sudo: false
language: node_js
node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: makewebsites.tonyhhyip.me
  on:
    branch: master